// Code generated by "stringer -type=IsolationLevel -trimprefix Level"; DO NOT EDIT.

package rdb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LevelDefault-0]
	_ = x[LevelReadUncommitted-1]
	_ = x[LevelReadCommitted-2]
	_ = x[LevelWriteCommitted-3]
	_ = x[LevelRepeatableRead-4]
	_ = x[LevelSerializable-5]
	_ = x[LevelSnapshot-6]
}

const _IsolationLevel_name = "DefaultReadUncommittedReadCommittedWriteCommittedRepeatableReadSerializableSnapshot"

var _IsolationLevel_index = [...]uint8{0, 7, 22, 35, 49, 63, 75, 83}

func (i IsolationLevel) String() string {
	if i >= IsolationLevel(len(_IsolationLevel_index)-1) {
		return "IsolationLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IsolationLevel_name[_IsolationLevel_index[i]:_IsolationLevel_index[i+1]]
}
