// Copyright (c) 2011, The pg Authors. All Rights Reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.

// +build ignore

// Generate the table of OID values. Run with 'go run gen.go'.
package main

import (
	"fmt"
	"log"
	"os"
	"os/exec"

	_ "bitbucket.org/kardianos/rdb/pg"
	"database/sql"
)

var header = `// Copyright (c) 2011, The pg Authors. All Rights Reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.

// Generated by 'go run gen.go'. Do not edit by hand.
`

func main() {
	datname := os.Getenv("PGDATABASE")
	sslmode := os.Getenv("PGSSLMODE")

	if datname == "" {
		os.Setenv("PGDATABASE", "pggotest")
	}

	if sslmode == "" {
		os.Setenv("PGSSLMODE", "disable")
	}

	db, err := sql.Open("postgres", "")
	if err != nil {
		log.Fatal(err)
	}
	cmd := exec.Command("gofmt")
	cmd.Stderr = os.Stderr
	w, err := cmd.StdinPipe()
	if err != nil {
		log.Fatal(err)
	}
	f, err := os.Create("types.go")
	if err != nil {
		log.Fatal(err)
	}
	cmd.Stdout = f
	err = cmd.Start()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Fprintln(w, header)
	fmt.Fprintln(w, "\npackage oid")
	fmt.Fprintln(w, "const (")
	rows, err := db.Query(`
		SELECT typname, oid
		FROM pg_type WHERE oid < 10000
		ORDER BY oid;
	`)
	if err != nil {
		log.Fatal(err)
	}
	var name string
	var oid int
	for rows.Next() {
		err = rows.Scan(&name, &oid)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Fprintf(w, "T_%s Oid = %d\n", name, oid)
	}
	if err = rows.Err(); err != nil {
		log.Fatal(err)
	}
	fmt.Fprintln(w, ")")
	w.Close()
	cmd.Wait()
}
