// Code generated by "stringer -type tdsToken -trimprefix token"; DO NOT EDIT.

package ms

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tokenLoginAck-173]
	_ = x[tokenError-170]
	_ = x[tokenInfo-171]
	_ = x[tokenDone-253]
	_ = x[tokenReturnStatus-121]
	_ = x[tokenReturnValue-172]
	_ = x[tokenDoneProc-254]
	_ = x[tokenDoneInProc-255]
	_ = x[tokenColumnMetaData-129]
	_ = x[tokenRow-209]
	_ = x[tokenNBCRow-210]
	_ = x[tokenEnvChange-227]
	_ = x[tokenOrder-169]
}

const (
	_tdsToken_name_0 = "ReturnStatus"
	_tdsToken_name_1 = "ColumnMetaData"
	_tdsToken_name_2 = "OrderErrorInfoReturnValueLoginAck"
	_tdsToken_name_3 = "RowNBCRow"
	_tdsToken_name_4 = "EnvChange"
	_tdsToken_name_5 = "DoneDoneProcDoneInProc"
)

var (
	_tdsToken_index_2 = [...]uint8{0, 5, 10, 14, 25, 33}
	_tdsToken_index_3 = [...]uint8{0, 3, 9}
	_tdsToken_index_5 = [...]uint8{0, 4, 12, 22}
)

func (i tdsToken) String() string {
	switch {
	case i == 121:
		return _tdsToken_name_0
	case i == 129:
		return _tdsToken_name_1
	case 169 <= i && i <= 173:
		i -= 169
		return _tdsToken_name_2[_tdsToken_index_2[i]:_tdsToken_index_2[i+1]]
	case 209 <= i && i <= 210:
		i -= 209
		return _tdsToken_name_3[_tdsToken_index_3[i]:_tdsToken_index_3[i+1]]
	case i == 227:
		return _tdsToken_name_4
	case 253 <= i && i <= 255:
		i -= 253
		return _tdsToken_name_5[_tdsToken_index_5[i]:_tdsToken_index_5[i+1]]
	default:
		return "tdsToken(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
